class Recipe {
  String label;
  String imageUrl;

  int servings;
  List<Ingredient> ingredients;

  Recipe(this.label, this.imageUrl, this.servings, this.ingredients);

  static List<Recipe> samples = [
    Recipe(
      'Lontong Kupang',
      'assets/Lontong Kupang.png',
      1,
      [
        Ingredient(200, 'gram', ' Kupang'),
        Ingredient(3, 'cm', ' Jahe'),
        Ingredient(3, 'lembar', ' Daun salam'),
        Ingredient(6, 'lembar', ' Daun jeruk purut'),
        Ingredient(0.5, 'sdt', ' Merica bubuk'),
        Ingredient(1, 'sdt', ' Garam'),
        Ingredient(0.25, 'sdt', ' Gula pasir'),
        Ingredient(1, 'ikat', ' Daun bawang merah, iris 2 cm'),
        Ingredient(1500, 'ml', ' Air untuk merebus'),
        Ingredient(1, 'buah', ' Cabai rawit'),
        Ingredient(1, 'sdt', ' Petis udang'),
        Ingredient(6, 'siung', ' Bawang putih, iris tipis'),
        Ingredient(4, 'buah', ' Lontong, potong-potong'),
        Ingredient(1, 'tusuk', ' Sate kerang'),
      ],
    ),
    Recipe(
      'Nasi Krawu',
      'assets/Nasi Krawu.png',
      1,
      [
        Ingredient(3, 'buah', ' Cabe merah'),
        Ingredient(1, 'sdt', ' Ketumbar'),
        Ingredient(2, 'sdm', ' Gula pasir'),
        Ingredient(5, 'buah', ' Cabe merah'),
        Ingredient(15, 'buah', ' Cabe kecil'),
        Ingredient(3, 'siung', ' Bawang putih'),
        Ingredient(10, 'buah', ' Bawang merah'),
        Ingredient(1, 'sdt', ' Terasi bakar'),
        Ingredient(0.25, 'sdt', ' Asam jawa'),
        Ingredient(1, 'sdt', ' Gula merah'),
      ],
    ),
    Recipe(
      'Nasi Tempong',
      'assets/Nasi Tempong.png',
      1,
      [
        Ingredient(1, 'siung', ' Bawang putih'),
        Ingredient(5, 'buah', ' Cabai merah'),
        Ingredient(1, 'buah', ' Tomat'),
        Ingredient(1, 'buah', ' Terasi goreng secukupnya'),
        Ingredient(0.5, 'sdt', ' Garam dan gula sesuai selera'),
      ],
    ),
    Recipe(
      'Pecel Madiun',
      'assets/Pecel Madiun.png',
      1,
      [
        Ingredient(100, 'gram', 'Tauge, siangi, rebus'),
        Ingredient(2, 'ikat', 'Bayam, siangi, rebus'),
        Ingredient(2, 'buah', 'Timun krau, jika ada, rebus'),
        Ingredient(1, 'ikat', 'Daun singkong'),
        Ingredient(50, 'gram', 'Kacang panjang, potong rebus'),
        Ingredient(1, 'ikat', 'Daun kacang, siangi'),
        Ingredient(50, 'gram', 'Bunga turi, buang bunga sarinya, rebus'),
        Ingredient(250, 'gram', 'Kacang tanah, goreng'),
        Ingredient(5, 'siung', 'Bawang putih, goreng'),
        Ingredient(3, 'buah', 'Cabai merah, goreng'),
        Ingredient(1, 'ruas', 'Kencur'),
        Ingredient(10, 'buah', 'Cabai rawit, goreng'),
        Ingredient(0.5, 'sdt', 'Air asam jawa'),
        Ingredient(5, 'lembar', 'Daun jeruk'),
        Ingredient(2, 'sdt', 'Gula merah'),
        Ingredient(1, 'buah', 'Timun, potong kotak'),
      ],
    ),
    Recipe(
      'Rawon',
      'assets/Rawon.png',
      1,
      [
        Ingredient(500, 'gram', 'Daging sandung lamur (brisket)'),
        Ingredient(6, 'lembar', 'Daun jeruk'),
        Ingredient(3, 'batang', 'Serai, geprek'),
        Ingredient(3, 'liter', 'Air'),
        Ingredient(1, 'ruas', 'Lengkuas, geprek'),
        Ingredient(8, 'siung', 'Bawang merah'),
        Ingredient(5, 'siung', 'Bawang putih'),
        Ingredient(4, 'buah', 'Kluwek ukuran sedang, keruk isinya'),
        Ingredient(4, 'butir', 'Kemiri, sangrai'),
        Ingredient(2, 'cm', 'Kunyit'),
        Ingredient(1.5, 'sdt', 'Ketumbar bubuk'),
        Ingredient(1, 'cm', 'Jahe'),
        Ingredient(1, 'batang', 'Bawang perai dipotong-potong'),
      ],
    ),
    Recipe(
      'Rujak Cingur',
      'assets/Rujak Cingur.png',
      1,
      [
        Ingredient(150, 'gram', 'Cingur sapi'),
        Ingredient(
            1, 'ikat', 'Kangkung, siangi daunnya kemudian rebus dan tiriskan'),
        Ingredient(
            100, 'gram', 'Taoge, siangi ekornya kemudian rebus dan tiriskan'),
        Ingredient(1, 'buah', 'Mentimun, potong 1 cm'),
        Ingredient(1, 'buah', 'Mentimun krai, kukus hingga lunak'),
        Ingredient(2, 'kotak', 'Tempe goreng, potong'),
        Ingredient(2, 'kotak', 'Tahu putih goreng, potong'),
        Ingredient(1, 'buah', 'Lontong, potong'),
        Ingredient(50, 'gram', 'Kacang tanah goreng'),
        Ingredient(2, 'siung', 'Bawang putih, goreng sampai layu'),
        Ingredient(3, 'buah', 'Cabai rawit merah'),
        Ingredient(1, 'sendok makan', 'Gula merah'),
        Ingredient(0.5, 'sendok teh', 'Terasi goreng'),
        Ingredient(0.5, 'sendok teh', 'Garam'),
        Ingredient(2, 'sendok makan', 'Petis udang'),
        Ingredient(3, 'sendok makan', 'Air asam'),
      ],
    ),
    Recipe(
      'Rujak Soto',
      'assets/Rujak Soto.png',
      1,
      [
        Ingredient(1, 'papan', 'Tempe'),
        Ingredient(1, 'buah', 'Mentimun'),
        Ingredient(2, 'buah', 'Lontong'),
        Ingredient(2, 'buah', 'Tahu putih'),
        Ingredient(0.1, 'kg', 'Tauge'),
        Ingredient(0.15, 'kg', 'Kangkung'),
        Ingredient(0.2, 'kg', 'Daging sapi'),
        Ingredient(2, 'batang', 'Seledri'),
        Ingredient(2, 'batang', 'Daun bawang'),
        Ingredient(2, 'batang', 'Serai'),
        Ingredient(2, 'cm', 'Lengkuas'),
        Ingredient(6, 'lembar', 'Daun jeruk'),
        Ingredient(0.1, 'kg', 'Kacang tanah'),
        Ingredient(2, 'sendok makan', 'Petis'),
        Ingredient(2, 'buah', 'Pisang mentah'),
        Ingredient(1, 'sendok makan', 'Air asam jawa'),
        Ingredient(1, 'sendok teh', 'Gula merah'),
        Ingredient(1, 'sendok teh', 'Garam'),
      ],
    ),
    Recipe(
      'Soto Lamongan',
      'assets/Soto Lamongan.png',
      1,
      [
        Ingredient(1, 'ekor', 'Ayam kampung (1 kg)'),
        Ingredient(2, 'liter', 'Air'),
        Ingredient(3, 'sendok makan', 'Minyak sayur'),
        Ingredient(2, 'batang', 'Daun bawang, potong kasar'),
        Ingredient(2, 'batang', 'Serai, memarkan'),
        Ingredient(3, 'lembar', 'Daun jeruk purut'),
        Ingredient(3, 'lembar', 'Daun salam'),
        Ingredient(3, 'cm', 'Lengkuas, memarkan'),
        Ingredient(5, 'siung', 'Bawang putih'),
        Ingredient(3, 'butir', 'Bawang merah'),
        Ingredient(4, 'buah', 'Kemiri, bakar dan haluskan'),
        Ingredient(4, 'cm', 'Kunyit, bakar dan haluskan'),
        Ingredient(1.5, 'sendok teh', 'Merica butiran'),
        Ingredient(2, 'sendok teh', 'Gula pasir'),
        Ingredient(2, 'sendok teh', 'Garam'),
      ],
    ),
    Recipe(
      'Tahu Campur',
      'assets/Tahu Campur.png',
      1,
      [
        Ingredient(3, 'buah', 'Tahu putih besar'),
        Ingredient(0.5, 'kg', 'Mie kuning'),
        Ingredient(0.1, 'kg', 'Tauge, seduh hingga layu'),
        Ingredient(4, 'buah', 'Lontong, potong-potong'),
        Ingredient(0.5, 'kg', 'Daging sandung lamur sapi, potong-potong'),
        Ingredient(2, 'liter', 'Air'),
        Ingredient(0.03, 'kg', 'Gula merah'),
        Ingredient(4, 'sendok makan', 'Kecap manis'),
        Ingredient(1, 'cm', 'Lengkuas'),
        Ingredient(2, 'lembar', 'Daun jeruk'),
        Ingredient(1, 'batang', 'Serai, memarkan'),
        Ingredient(3, 'siung', 'Bawang putih'),
        Ingredient(5, 'butir', 'Bawang merah'),
        Ingredient(2, 'cm', 'Kunyit'),
        Ingredient(0.5, 'sendok teh', 'Merica butiran'),
        Ingredient(0.5, 'sendok teh', 'Jinten'),
        Ingredient(1, 'sendok teh', 'Garam'),
        Ingredient(10, 'buah', 'Cabe rawit hijau'),
        Ingredient(5, 'sendok makan', 'Petis udang'),
        Ingredient(0.5, 'sendok teh', 'Garam'),
        Ingredient(0.25, 'liter', 'Air hangat'),
      ],
    ),
    Recipe(
      'Tahu Tek',
      'assets/Tahu Tek.png',
      1,
      [
        Ingredient(1.5, 'buah', 'Tahu putih besar'),
        Ingredient(2, 'butir', 'Telur ayam'),
        Ingredient(1, 'buah', 'Kentang, rebus dan kupas kulitnya'),
        Ingredient(0.05, 'kg', 'Taoge pendek, rendam air panas'),
        Ingredient(2, 'buah', 'Lontong'),
        Ingredient(2, 'batang', 'Seledri, iris halus'),
      ],
    ),
  ];
}

class Ingredient {
  double quantity;
  String measure;
  String name;

  Ingredient(this.quantity, this.measure, this.name);
}
